# Generated by Django 4.2.1 on 2023-10-03 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="username",
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True, max_length=300, null=True)),
                ("division", models.CharField(blank=True, max_length=50)),
                ("dob", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.BooleanField(
                        blank=True,
                        choices=[("Male", "Male"), ("Female", "Female")],
                        null=True,
                    ),
                ),
                ("hr_number", models.CharField(max_length=20)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
